### ISSUE TITLE
Recorder 

### ISSUE THREAD

**Issue by chaksoham** [saucepleez/sharpRPA#20]
Hey, do you plan on building a recorder as in to capture windows activity and then replay them.I am trying to work on a similar problem, it will be great to collaborate.

**Comment by chaksoham** [comment]
We have developed a recorder using electron, i was thinking if we can have something on similar thing here.

**Comment by saucepleez** [comment]
So to clarify, you are looking for functionality to record the screen and replay that back as a video file or some other video format?  Or record the actions that a user is doing (so capturing mouse clicks, keystrokes, etc) and then "replay" that back?

**Comment by chaksoham** [comment]
Record the actions that a user is doing and then "replay" back .

**Comment by chaksoham** [comment]
could you post a workflow with ocr example, I am  trying to use the ocr event but its processing for a long time.No output

**Comment by chaksoham** [comment]
sharpRPA.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\tejsingh\Desktop\sharpRPA-master\sharpRPA-master\sharpRPA\bin\Debug\sharpRPA.exe'. Symbols loaded.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'Microsoft.GeneratedCode'. 
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded '**OneNoteOCRDll'. Cannot find or open the PDB file.
Exception thrown: 'System.Data.SyntaxErrorException' in System.Data.dll
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded** 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'sharpRPA.exe' (CLR v4.0.30319: sharpRPA.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.OneNote\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.OneNote.dll'. Module was built without symbols.
The thread 0x1134 has exited with code 0 (0x0).
Exception thrown: 'System.Data.SyntaxErrorException' in System.Data.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.dll
Exception thrown: 'System.Exception' in sharpRPA.exe
An exception of type 'System.Exception' occurred in sharpRPA.exe but was not handled in user code
System.Runtime.InteropServices.COMException (0x80080005): Retrieving the COM class factory for component with CLSID {D7FAC39E-7FF1-49AA-98CF-A1DDD316337E} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(RuntimeType serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(RuntimeType serverType, Object[] props, Boolean bNewObj)
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OneNoteOCRDll.OneNoteOCR.FromImage(String imagePath)
   at OneNoteOCRDll.OneNoteOCR.<OcrTexts>d__4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at sharpRPA.Core.AutomationCommands.OCRCommand.RunCommand(Object sender) in C:\Users\tejsingh\Desktop\sharpRPA-master\sharpRPA-master\sharpRPA\Core\AutomationCommands.cs:line 2618
   at sharpRPA.UI.Forms.frmScriptEngine.ExecuteCommand(ScriptAction command, BackgroundWorker bgw) in C:\Users\tejsingh\Desktop\sharpRPA-master\sharpRPA-master\sharpRPA\UI\Forms\frmScriptEngine.cs:line 162

​

**Comment by chaksoham** [comment]
working environment , windows server 2012 r2 (64 bit)

**Comment by atotalnoob** [comment]
OneNote has to be installed for OCR to work.


It uses the onenote OCR engine to do all OCR.

**Comment by chaksoham** [comment]
Thanks a lot , it worked. One more thing how to maximize the web browser (current instance ) . The current window state is not able to capture it. Any idea on how to do it ?

**Comment by chaksoham** [comment]
@saucepleez I have added you. Do check, it's a private repo. Let me know if there are other medium we can communicate with as in messenger. Thanks

**Comment by saucepleez** [comment]
Maximize Browser support added for Selenium Browser Creation command.

**Comment by chaksoham** [comment]
@saucepleez , hi have a look into this http://www.softwaretestinghelp.com/sikuli-tutorial-part-1/ , this is a screenshot based approach, to record the screen action. If we can integrate the same in here.

**Comment by atotalnoob** [comment]
Neat, so you do it. It's open source, you can integrate it

**Comment by chaksoham** [comment]
Yep, I am java developer, that's why finding it difficult, if you can guide me to how directly integrate this, it would be of great help. I am going through the code base, to get an understanding.

**Comment by saucepleez** [comment]
I don't think you would want to directly integrate that project -- what you are talking about doing is simple image recognition on the screen.  You take a subset of data (smaller image) and search pixel by pixel through a larger image (desktop image) until you find a matching pattern.  So to make that happen in this project, you would need to simply create a new Image Recognition command class, added to AutomationCommands.cs in the same design pattern as all other items in the same class:

    [Serializable]
    [Attributes.ClassAttributes.Group("Image Commands")]
    [Attributes.ClassAttributes.Description("This command attempts to find an existing image on screen.")]
    [Attributes.ClassAttributes.ImplementationDescription("TBD")]
    public class ImageRecognitionCommand : ScriptCommand
    {
        [XmlAttribute]
        [Attributes.PropertyAttributes.PropertyDescription("Path to comparison file")]
        public string v_ComparisonImageFilePath { get; set; }

        [XmlAttribute]
        [Attributes.PropertyAttributes.PropertyDescription("Please Select an Action")]
        [Attributes.PropertyAttributes.PropertyUISelectionOption("Click Location")]
        [Attributes.PropertyAttributes.PropertyUISelectionOption("Move Mouse To Location")]
        public string v_CommandAction { get; set; }

        public ImageRecognitionCommand()
        {
            this.CommandName = "ImageRecognitionCommand";
            this.SelectionName = "Image - Image Recognition";
            this.CommandEnabled = true;
        }
        public override void RunCommand(object sender)
        {
           //get image from v_ComparisonImageFilePath
           //get current screenshot from desktop window
          //loop desktop window screenshot and see if v_ComparisonImageFilePath is contained
          //if found, verify user's intent of v_CommandAction and handle accordingly
         //if not found, throw exception
        }
        public override string GetDisplayValue()
        {
            return base.GetDisplayValue() + " [Comparison File: " + v_ComparisonImageFilePath + "]";
        }
    }

Once you put this class into AutomationCommands.cs it will automatically show in the project.  There are more ways however to create a "smarter" recorder as well -- in C# you can hook the mouse and keyboard events to better record user actions for desktop automation.  Web automation is more complicated as it will require a custom extension/socket server. Automation by image recognition alone is not very robust in itself, typically it would be used as a failover or in combination with other methods (window handles, etc).

**Comment by chaksoham** [comment]
Superb, thanks will look into it for the recording, agreed the image based recognition fails in many cases and needs to be augmented with event listeners  (mouse and keyboard ). Also, i see a command to send keyboard input ( how do u manage to send special characters? The input field only asks for string to input)

**Comment by atotalnoob** [comment]
You could send them via ASCII code or escape them. To declare a literal
string just put @ in front. So

string string = @"this is a literal";

**Comment by chaksoham** [comment]
got it , thanks for the fast reply

**Comment by chaksoham** [comment]
So the idea has I looked up hooks, we can capture events from the keyboard, are you aware of any library that can capture mouse hover events (as in we take the mouse over an object and capture the details, automation id and other details from it ).

**Comment by saucepleez** [comment]
C# works directly with the Windows API, you can hook both keyboard and mouse to capture, no library needed.

So now using Windows API:
- Hook Keystrokes Sent
- Hook Mouse Move Events (https://blogs.msdn.microsoft.com/toub/2006/05/03/low-level-mouse-hook-in-c/)
- Hook Mouse Click (https://stackoverflow.com/questions/11607133/global-mouse-event-handler)

Goal:
When any of the events above occur, add them to a List<HookedAction> (List of HookedAction Class). 
 When a mouse click occurs, you can also pull other data such as the pixels surrounding the mouse, currently active window name, mouse coordinates, etc. Add those fields to the HookedAction as well.

After user stops recording, you then iterate through those logged events and generate the comparable command in the UI:

                    foreach (var hookedAction in HookedActions)
                    {
                       if(hookedAction.Name == "MouseMoveAction"){

                            SendMouseMoveCommand newMouseMove = new SendMouseMoveCommand();
                            newMouseMove,v_XMousePosition = hookedAction.X;
                            newMouseMove,v_YMousePosition = hookedAction.Y;
                            
                           //add command to main listview

                             }

                    }

  `

**Comment by saucepleez** [comment]
I have pushed an Image Recognition command with basic image recognition functionality.  It creates a fingerprint of 5 points on the screen and then loops the screen height and width until it finds all 5 corresponding point colors.

It probably needs to be "smarter" in the sense that the fingerprint should be based on a larger potential sampling.

**Comment by chaksoham** [comment]
I am looking into jnative hook , its a java implementation of the same , abstracts the c++ code ,
https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/example/NativeHookDemo.java

**Comment by saucepleez** [comment]
Again, this project does not need any of that since you can expose Win32 in C#.  We are not planning to merge any Java into the code base as it is going to complicate the project regarding deployment.  Please raise a new issue for any further questions, comments, concerns.
