### ISSUE TITLE
Document the steps to build from source

### ISSUE THREAD

**Issue by chaksoham** [saucepleez/sharpRPA#21]
Hey it would be very helpful if you could, a document on how to build in visual studio.
![screenshot from 2018-02-06 19-42-13](https://user-images.githubusercontent.com/5665492/35863856-ff11e79c-0b75-11e8-8b21-4765460f6e3d.png)

**Comment by chaksoham** [comment]
Hey, finally got it working, was using community edition, that's why was not working.

**Comment by saucepleez** [comment]
I use community edition currently, not sure why that was an issue.  Could you provide a better description in case anyone else is experiencing this same issue? We can add that to the Wiki.
