### ISSUE TITLE
Missing NuGet packages

### ISSUE THREAD

**Issue by atotalnoob** [saucepleez/sharpRPA#6]
Hi, 

The current build is missing a nuGet package - SPecifically the RibbonLib package. This is preventing the project from compiling.

After adding the package manually, visual studio froze up and wouldn't reopen this solution. 

Automatic nuGet restoration didn't work. Even adding:
```
 <packageRestore>
        <add key="enabled" value="True" />
    </packageRestore>
```

to the nuget.config file.

**Comment by saucepleez** [comment]
RibbonLib was removed so I will adjust the project accordingly.  It was recommended elsewhere to push the code to the repository (sans nuget packages) and then let developers resolve the nuget references locally.  Perhaps that is something we should look at changing.

**Comment by saucepleez** [comment]
I have removed the RibbonLib referenced and synchronized the commit.  Closing issue.
